### PR TITLE
[ready] Doc and cleanup

### PR DESCRIPTION
**Pull request by alberth**
@MatthijsBurgh I don't know exactly who else has interest in this, but it would seem useful imho to invite others to chime in as well.

I found this package to be a good target to start documenting (small and simple, so easy to do, and simple to change), and since I was asked about how to add documentation to the CPP code, I made this PR as an example, and point of discussing what is desired.

The entire idea about adding Doxygen documentation (doxymentation) is to create a second, higher level reference what the function/method is doing. It should contain all information required to use the function, which includes

1. What does the function do.
2. What are its arguments, in particular value ranges, and meaning of values (units, meaning of special values like ``0``, are negative values allowed, and what do they do, etc)
3. What output does the function give me, in terms of functionality and the input parameters.

In other words, with the text and the function header, you can call the function and know what to expect from it. Since we are much faster in reading 6 lines of text than we are in decoding 50+ lines of cpp code (in particular wrt edge cases and meaning of values), this actually speeds up your work.

Adding a second description introduces the possibility of inconsistencies, ie the code may do something else than the text says. Decisions how to unify it again should be made on common sense, but using the text as leading works best in my experience, since that is what all calls used, and it gives a high level intentional description which is likely to be more stable over a longer period of time.

== About the commits attached to this Pr ==

Obviously, most things I changed are according to my preferences, but that doesn't imply this is how it should become. Documentation style and coding style are highly debated topics, the primary goal should be imho to get an agreement on what to do. This PR is an example of what can be changed, to start a discussion. I'll have no problem reverting some of the proposed changes if that helps in agree-ing on a documentation and code style. Making other changes can be done too, as far as I am concerned.

It is probably best to read each commit separately, below is a short explanation of why I made some changes. Also, you may want to see the 'before' and 'after' version of the files, as that gives a better impression how file looks.

cef6f5e5c8857a10a98690c4fd7e3a6fc6556eab
* @file header must be added to each file for Doxygen, or it doesn't process the comments.
* The consistent double lines in the entire file defeats the option to make groups of related functions/methods. I think having groups of related functions is useful to have.
* One block comment seems to give the least amount of clutter. I use 2 styles, either everything on a single line, or a ``/**`` at the first line and the ``*/`` below the doxyment.
* I use ``@`` rather than ``\`` mostly out of habit, Doxygen treats them as equivalent afaik.
* There is usually no need for explicit ``@brief`` and ``@detail``, the first sentence is the brief description, everything else is details.
* I add the documentation to the definition of the function, ie near the code. That increases the chance of keeping them consistent. Also, since code is large already, adding the comment doesn't add much clutter.
* You can also add comment after the definition. This makes a lot of sense with variables, (eg crawler.h new line 60-64) I used ``///<` as prefix, Doxygen has several other forms.
* Adding a comment near the end of the namespace made sense to me.
* In the cpp code, the ``----------------------`` lines aren't much needed anymore, the doxyment text serves as separator.
* In the text I used ``#method`` to create a link to the mentioned method, ``\c stuff`` to make ``stuff`` be formatted in code tags, and ``\a arg`` to refer to other arguments of a function.

0d3bb0e5847dbaf5b1c29e7e3b550d1eb9aa21f6

* This is mostly about reducing vertical space, having curly brackets on a separate line means you're wasting almost half the lines of your display. Also, it makes groups of code invisible, as almost every second line looks like a separator line.
* I made the outermost curly brackets of a function always at a separate line, which is somewhat a contradiction to the previous point. Mostly this is about consistency, another option can be to move the opening bracket of a method to the end of the function header line everywhere.
* In the ``nextPath`` function, the effect of not using separate lines for curly brackets is most clear. It reduces the function from 52 to 40 lines, while adding a comment line above each of the 2 steps.
* The unbracketed multi-line statement (like line 54 in old path.cpp) is quite fragile, it is easy to make mistakes there. I changed it either to a bracketed version, or to a single line version (eg line 88 in the new crawler.cpp file).

As a final note, at some point functions become so trivial that documentation is almost useless. Not documenting such functions is an option of course, but that opens the problem of deciding _what is trivial enough?_ I avoid that entire problem by just documenting everything. Such trivial functions are also trivial to document, so such discussion is soon taking more time than just writing a few lines of comment.

== Converting everything else ==
As for converting the entire code base, I believe we should first agree on some style for documentation and code, and fixate this by writing it down somewhere.
Next step would be stop accepting PRs that add functions without proper documentation.
To speed up the conversion, we could also stop accepting PRs that modify functions without proper documentation.
PRs that only add documentation are welcome, and imho very useful, but they are boring to write, so the quality of them is soon too low to be useful.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
I think it is useful for everybody to see this. @tue-robotics/amigo

**Comment by Rayman** [comment]
Looks good! For the code style (as with most things) we follow the ROS guidelines: http://wiki.ros.org/CppStyleGuide. You can find a `clang-format` config here for automatic formatting: https://github.com/davetcoleman/roscpp_code_format

**Comment by alberth** [comment]
ROS style guide refers to Google code style guide. ROS style also contradicts Google style in curly brace lines.

Both say to use 2 space indent, but having worked in a large Lua project that did this, I am glad this is not done here. Deeper nesting becomes impossible to parse, 2 spaces just isn't enough indenting to see easily, especially if the function is long.

**Comment by Rayman** [comment]
For old projects you can keep the style as is of course to avoid big commits that change lots of code. For new projects please use the correct style (and enforce it in the build when possible).

**Comment by alberth** [comment]
Personally, I believe that a guide that uses another document because "it is a well-written document on the topic at hand", and then contradicts with that guide without any explanation at all why the guide doesn't apply, should be carefully considered for its opinion. However, I reverted to the "curly brace at its own line" style as requested. I kept the expansion of the single statement methods in the header files to stay consistent with how you write a function.

I am aware that code style changes make major mess, the trick to do them is to separate code style changes from other changes so you can just ignore that commit. Also you shouldn't do them while other branches are in progress to avoid merge conflicts.

**Comment by Timple** [comment]
> a guide that uses another document because "it is a well-written document on the topic at hand", and then contradicts with that guide without any explanation at all why the guide doesn't apply

I think it is smart to refer to an other guide but you have a fair point about the missing explanations where the guide deviates.
In my opinion it is even worth opening an issue asking for clarification from the ROS developers!

**Review by MatthijsBurgh — APPROVED** [review]
Maybe a good idea to have a sample for documentation.

**Pull request merged**
