### PR TITLE
ignore CMakeLists.txt.user

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Review by hvrooy — COMMENTED** [review]
Why were these files needed? Why not anymore?

**Comment by MatthijsBurgh** [comment]
CMakelists.txt.user is created by QtCreator, but not needed by any other software.

**Review by samaleksandrov — APPROVED** [review]

**Comment by Timple** [comment]
Can't you just add CMakeLists.txt.user to your global gitignore? Instead of making a PR in every repo?

**Comment by MatthijsBurgh** [comment]
@Timple can we include it in a tue-env target?

See: https://github.com/tue-robotics/tue-env/pull/283

**Pull request merged**
